#!/usr/bin/env python3
import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

UUID_RE = re.compile(
    r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-"
    r"[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
)
MAPPER_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.+-]{0,126}$")

UNIT_PATH = Path("/etc/systemd/system/esp-key-autounlock.service")
RULE_PATH = Path("/etc/udev/rules.d/99-esp-key-autounlock.rules")


def fail(message):
    print(f"esp-key: {message}", file=sys.stderr)
    raise SystemExit(1)


def mapper_name(value):
    if not MAPPER_RE.fullmatch(value):
        raise argparse.ArgumentTypeError("invalid mapper name")
    return value


def systemd_quote(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def get_uuid(device):
    result = subprocess.run(
        ["cryptsetup", "luksUUID", device],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        fail((result.stderr or result.stdout).strip() or f"{device} is not LUKS")
    uuid = result.stdout.strip().lower()
    if not UUID_RE.fullmatch(uuid):
        fail("cryptsetup returned an invalid LUKS UUID")
    return uuid


def write_config(device, name):
    uuid = get_uuid(device)
    # Keep the venv launcher itself instead of resolving its symlink to the
    # system interpreter; pyserial is installed in this venv.
    python = os.path.abspath(sys.executable)
    helper = str((Path(__file__).resolve().parent / "auto_unlock.py").resolve())

    if any(c.isspace() for c in python):
        fail("Python executable path contains whitespace; move the venv to a simpler path")
    if not Path(helper).is_file():
        fail(f"missing helper: {helper}")

    unit = f"""[Unit]
Description=ESP-Key automatic unlock for LUKS {uuid}
After=systemd-udevd.service

[Service]
Type=oneshot
ExecStart={systemd_quote(python)} {systemd_quote(helper)} --uuid {uuid} --name {name}
"""

    rules = f"""# Generated by esp-key install_autounlock.py
# Trigger when the enrolled LUKS volume appears.
ACTION=="add", SUBSYSTEM=="block", ENV{{ID_FS_TYPE}}=="crypto_LUKS", ENV{{ID_FS_UUID}}=="{uuid}", TAG+="systemd", ENV{{SYSTEMD_WANTS}}+="esp-key-autounlock.service"
ACTION=="change", SUBSYSTEM=="block", ENV{{ID_FS_TYPE}}=="crypto_LUKS", ENV{{ID_FS_UUID}}=="{uuid}", TAG+="systemd", ENV{{SYSTEMD_WANTS}}+="esp-key-autounlock.service"

# Trigger when an Espressif USB serial device appears. The helper still probes
# the ESP-Key protocol, so another ESP board cannot unlock the volume merely by existing.
ACTION=="add", SUBSYSTEM=="tty", ATTRS{{idVendor}}=="303a", TAG+="systemd", ENV{{SYSTEMD_WANTS}}+="esp-key-autounlock.service"
"""

    UNIT_PATH.write_text(unit, encoding="utf-8")
    RULE_PATH.write_text(rules, encoding="utf-8")
    os.chmod(UNIT_PATH, 0o644)
    os.chmod(RULE_PATH, 0o644)

    subprocess.run(["systemctl", "daemon-reload"], check=True)
    subprocess.run(["udevadm", "control", "--reload-rules"], check=True)
    subprocess.run(
        ["systemctl", "reset-failed", "esp-key-autounlock.service"],
        check=False,
    )

    print(f"Installed ESP-Key auto-unlock for LUKS UUID {uuid}")
    print(f"Mapper name: /dev/mapper/{name}")
    print("It will trigger when either the encrypted drive or ESP-Key is plugged in.")


def uninstall():
    changed = False
    for path in (UNIT_PATH, RULE_PATH):
        try:
            path.unlink()
            changed = True
        except FileNotFoundError:
            pass
    subprocess.run(["systemctl", "daemon-reload"], check=True)
    subprocess.run(["udevadm", "control", "--reload-rules"], check=True)
    if changed:
        print("Removed ESP-Key auto-unlock.")
    else:
        print("ESP-Key auto-unlock was not installed.")


def main():
    parser = argparse.ArgumentParser(
        description="Install ESP-Key udev/systemd auto-unlock"
    )
    parser.add_argument("device", nargs="?", help="enrolled LUKS device, e.g. /dev/sda")
    parser.add_argument("--name", type=mapper_name, default="esp-key-usb")
    parser.add_argument("--uninstall", action="store_true")
    args = parser.parse_args()

    if os.geteuid() != 0:
        fail("run this installer with sudo")

    if args.uninstall:
        uninstall()
        return

    if not args.device:
        parser.error("device is required unless --uninstall is used")
    write_config(args.device, args.name)


if __name__ == "__main__":
    main()
